parcellab/common/Chart.yaml, parcellab/common/templates/_pod.tpl, parcellab/cronjob/Chart.yaml, parcellab/microservice/Chart.yaml, parcellab/monolith/Chart.yaml, parcellab/worker-group/Chart.yaml
Some teams need to manage the case in which they need to map a hostname to an ip address. This PR gives the ability to teams to configure such mappings in their pod spec
=> feat: add host aliases to pod

parcellab/common/Chart.yaml, parcellab/common/templates/_configmap.tpl, parcellab/common/templates/_cronjob.tpl, parcellab/common/templates/_deployment.tpl, parcellab/common/templates/_externalsecret.tpl, parcellab/common/templates/_ingress.tpl, parcellab/common/templates/_job.tpl, parcellab/common/templates/_labels.tpl, parcellab/common/templates/_names.tpl, parcellab/common/templates/_pod.tpl, parcellab/common/templates/_service.tpl, parcellab/cronjob/Chart.yaml, parcellab/monolith/Chart.yaml, parcellab/monolith/templates/service.yaml, parcellab/worker-group/Chart.yaml
When having complex deployments with multiple components (e.g. a monolith application with different entry points), there is no way currently to differentiate selectors, making impossible to have multiple services.
This PR
- Fixes a bug in which the default service in the `monolith` chart would not be created if an extraService is given
- Defines a new `component` label to be use as selector when multiple resources are defined in a single chart
=> fix: add component selectors

parcellab/microservice/templates/cronjob.yaml, parcellab/monolith/templates/cronjob.yaml
Bug: single cronjob element not. contemplated in in microservice and monolith charts
Adding single cronjob template for microservice and monolith
=> fix: adding single cronjob template for microservice and monolith

parcellab/monolith/templates/cronjobs.yaml
In order to fix the bug that cronjobs default to [ ] and merging with template context with enabled: true we need to ensure cronjobs only get created when they have the name attribute set in the monolith chart
=> fix: enable cronjobs only when name is present in monolith

parcellab/monolith/Chart.yaml, parcellab/monolith/templates/cronjob.yaml, parcellab/monolith/templates/cronjobs.yaml
template because just used for template values for each job defined in cronjobs attribute
=> fix: updated version of monolith to 0.0.21 removed obsolete cronjob.yaml

parcellab/cronjob/values.yaml, parcellab/microservice/values.yaml, parcellab/monolith/values.yaml, parcellab/worker-group/values.yaml
We need to introduce a default node selector for services that require “no specialties”, meaning the can be run on every node (on demand nodes as well as spot nodes) and don’t have specific requirements for e.g. networking. This should be then the default node selector passed through the charts or set if not specified.
https://parcellab.atlassian.net/browse/INF-500
=> feat: adding default provisioner for nodeSelector in charts

parcellab/common/Chart.yaml, parcellab/common/templates/_deployment.tpl, parcellab/common/values.yaml, parcellab/microservice/Chart.yaml, parcellab/microservice/values.yaml, parcellab/monolith/Chart.yaml, parcellab/monolith/values.yaml, parcellab/worker-group/Chart.yaml, parcellab/worker-group/values.yaml
In order to avoid downtime during deployments we are going to add strategies for rolling updates.
https://www.cncf.io/wp-content/uploads/2020/08/CNCF-Presentation-Template-K8s-Deployment.pdf
=> feat: adding strategy in deployment

parcellab/cronjob/Chart.yaml, parcellab/microservice/Chart.yaml, parcellab/monolith/Chart.yaml
dbt started to fail in prod due to the upgrade. Rolling back changes.
=> fix: rolling back versions for postgresql chart and redis chart

parcellab/common/templates/_job.tpl, parcellab/monolith/values.yaml
In order to support the cleanup for jobs this introduces the `hookDeletePolicy` setting for jobs.
https://argo-cd.readthedocs.io/en/stable/user-guide/resource_hooks/
=> feat: add support for ttlSecondsAfterFinished for jobs

parcellab/common/Chart.yaml, parcellab/common/templates/_deployment.tpl, parcellab/common/templates/_hpa.tpl, parcellab/monolith/Chart.yaml, parcellab/monolith/templates/hpa-services.yaml
https://parcellab.atlassian.net/browse/INF-1017
Adding template to use autoscaling(HPA) for extra services.
Fixing logic to use replicaCounts with extra services. If you enable HPA even if you settle replicaCount the autoscaling config prevails over the replicaCount anyway by default.
Fixing typo in common hpa template.
=> feat: adding autoscaling for extra services in monolith

parcellab/cronjob/Chart.yaml, parcellab/microservice/Chart.yaml, parcellab/worker-group/Chart.yaml
Forgot to update some charts versions to use latest common templates.
=> feat: updating parcellab charts with latest common templates

parcellab/common/Chart.yaml, parcellab/common/templates/_container.tpl, parcellab/common/templates/_pod.tpl, parcellab/cronjob/Chart.yaml, parcellab/microservice/Chart.yaml, parcellab/monolith/Chart.yaml, parcellab/worker-group/Chart.yaml
For some reason, the default value is always used even if you settle the `readOnly: false` in the `values.yaml`
=> feat: removing default value for readOnly parameter in volumes

parcellab/common/Chart.yaml, parcellab/common/templates/_job.tpl, parcellab/monolith/Chart.yaml, parcellab/monolith/values.yaml
there was a reason why it was not included, it does not work on jobs, only cronjobs, apparently TTL is the proper settings for jobs.
=> fix: remove job history limit / use TTL

parcellab/common/Chart.yaml, parcellab/common/templates/_deployment.tpl, parcellab/common/values.yaml, parcellab/microservice/Chart.yaml, parcellab/monolith/Chart.yaml, parcellab/monolith/values.yaml, parcellab/worker-group/Chart.yaml, parcellab/worker-group/values.yaml
& rename `disableReplicas` to `disableReplicaCount`, due to ambigous naming
=> chore: enable disabling of replica count on primary service for autoscaling

parcellab/common/Chart.yaml, parcellab/common/templates/_keda.tpl, parcellab/cronjob/Chart.yaml, parcellab/microservice/Chart.yaml, parcellab/monolith/Chart.yaml, parcellab/monolith/templates/keda-workers.yaml, parcellab/monolith/values.yaml, parcellab/worker-group/Chart.yaml
Now we can add a KEDA object from a worker definition. Only works with AWS SQS.
=> chore: create keda scaling from workers definition

parcellab/common/Chart.yaml, parcellab/common/templates/_datadog.tpl, parcellab/cronjob/Chart.yaml, parcellab/microservice/Chart.yaml, parcellab/monolith/Chart.yaml, parcellab/worker-group/Chart.yaml
In order to have an environment variable for statsD we want to add the DD_AGENT_HOST as env var.
=> feat: add DD_AGENT_HOST to the container env if datadog is enabled

parcellab/common/Chart.yaml, parcellab/common/templates/_datadog.tpl, parcellab/cronjob/Chart.yaml, parcellab/microservice/Chart.yaml, parcellab/monolith/Chart.yaml, parcellab/worker-group/Chart.yaml
It makes more sense to set this value by the other environment variable mechanisms. This is much more  flexible.
=> chore: revert adding DD_AGENT_HOST to the container env 

parcellab/common/Chart.yaml, parcellab/common/templates/_pod.tpl, parcellab/cronjob/Chart.yaml, parcellab/microservice/Chart.yaml, parcellab/monolith/Chart.yaml, parcellab/monolith/templates/deployment-workers.yaml, parcellab/monolith/values.yaml, parcellab/worker-group/Chart.yaml
the cluster autoscaler seems to be at the moment not moving our pods, as they have local host mounts.
also adds worker default values
=> fix: adds datadog socket volume safe-to-evict annotation

parcellab/common/templates/_hpa.tpl
https://parcellab.atlassian.net/browse/INF-1325
It seems the HPA template is not using the correct deployment name. This should fix it.
=> fix: fixing hpa template with deployment names

parcellab/common/Chart.yaml, parcellab/common/templates/_pod.tpl, parcellab/common/templates/_rollout.tpl, parcellab/common/templates/_service.tpl, parcellab/common/values.yaml, parcellab/cronjob/Chart.yaml, parcellab/microservice/Chart.yaml, parcellab/microservice/values.yaml, parcellab/monolith/Chart.yaml, parcellab/monolith/values.yaml, parcellab/worker-group/Chart.yaml, parcellab/worker-group/values.yaml
This pull request introduces the ability to specify extra ports for services and pods within the Helm chart, enhancing the flexibility of service definitions.
The change is required to allow users to define additional ports in the pod's container spec and in the service, which is essential for services that need to expose more than the default port. This is particularly useful for applications that serve multiple protocols or require additional ports for metrics, health checks, or other purposes.
The changes include:
- Modifying the `_service.tpl` template to iterate over an array of extra ports defined in `.Values.service.extraPorts`.
- Modifying the `_pod.tpl` template to iterate over an array of extra ports defined in `.Values.service.extraPorts`.
- Updating the `values.yaml` file to …
=> feat: Add support for extra ports in service and pod templates

parcellab/worker-group/Chart.yaml, parcellab/worker-group/templates/poddisruptionbudget-workers.yaml, parcellab/worker-group/templates/poddisruptionbudget.yaml
This PR includes a fix for the PodDisruptionBudget templates in the worker-group chart.
Fixing poddisruptionbudget templates for worker-group chart.
The PodDisruptionBudget templates had an issue causing an error on deployment.
The changes include:
- Creating additional template for extra workers.
The changes were tested by:
- Generating an example yaml file using the changes locally.
=> fix: Fixing templates for poddisruptionbudget in worker-group chart.

parcellab/common/Chart.yaml, parcellab/common/templates/_rollout.tpl, parcellab/cronjob/Chart.yaml, parcellab/microservice/Chart.yaml, parcellab/monolith/Chart.yaml, parcellab/worker-group/Chart.yaml
Argo rollout configuration for extra services in the monolith chart was using the global deployment name instead the name of the services.
Fixing the metadata name field in rollout template in the common chart.
=> fix: Fixing metadata name for rollout template in common chart.

parcellab/monolith/Chart.yaml, parcellab/monolith/templates/poddisruptionbudget-service.yaml, parcellab/monolith/templates/rollout-service.yaml
When defining more than two `extraServices` in the values file, the Helm chart fails with a YAML parsing error. This is due to the incorrect placement of the YAML document separator `---` which is generated after each `podDisruptionBudget` definition, even when the `podDisruptionBudget` is not present for a service. The error message is as follows:
`Error: YAML parse error on product-api/charts/monolith/templates/poddisruptionbudget-service.yaml: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type releaseutil.SimpleHead
`
Same issues with rollout.service.yaml.
The templates have been updated by changing the `{{- end -}}` to `{{- end }}`. This prevents the generation of empty YAML documents separated by `---` when there is no …
=> fix: Fix YAML parsing issue in poddisruptionbudget and rollout extraservices.

parcellab/monolith/Chart.yaml, parcellab/monolith/templates/cronjobs.yaml
This fixes the bug that the common values in the `cronjob` block for default values is not considered in the cronjob manifests. Currently the only the values from the top level were passed.
=> fix: inf-1597 Fixes the inheritance from the cronjob (default) block to cronjobs

parcellab/common/Chart.yaml, parcellab/common/templates/_cronjob.tpl, parcellab/cronjob/Chart.yaml, parcellab/cronjob/values.yaml, parcellab/microservice/Chart.yaml, parcellab/microservice/values.yaml, parcellab/monolith/Chart.yaml, parcellab/monolith/values.yaml, parcellab/worker-group/Chart.yaml
Adding the `timeZone` configuration for cronjobs in the common charts. 
Please note that the `timeZone` field is only available in Kubernetes version 1.21 and later.
https://parcellab.atlassian.net/browse/INF-1679
=> feat: Adding timeZone configuration for cronjobs.

parcellab/common/templates/_rollout.tpl, parcellab/cronjob/Chart.yaml, parcellab/microservice/Chart.yaml, parcellab/monolith/Chart.yaml, parcellab/worker-group/Chart.yaml
Changing the rollout preview services name to avoid confusion with preview environment.
=> feat: Changing rollout preview services name

.github/workflows/release.yaml
https://parcellab.atlassian.net/browse/INF-1799
Adding extra step to run release job only when charts are modified.
=> feat: INF-1799 adding extra step to run release job only when charts change

parcellab/cronjob/values.yaml, parcellab/microservice/values.yaml, parcellab/monolith/values.yaml, parcellab/worker-group/values.yaml
Removing default cpu limits, because we should be able to not specify them, and right now it causes these:
```
Deployment.apps "zelda-tracking-api" is invalid: spec.template.spec.containers[0].resources.requests: Invalid value: "500m": must be less than or equal to cpu limit of 250m```
=> fix: remove default cpu limits

parcellab/common/Chart.yaml, parcellab/common/templates/_deployment.tpl, parcellab/common/templates/_rollout.tpl, parcellab/cronjob/Chart.yaml, parcellab/microservice/Chart.yaml, parcellab/monolith/Chart.yaml, parcellab/monolith/templates/deployment.yaml, parcellab/monolith/templates/rollout-service.yaml, parcellab/monolith/templates/rollout.yaml, parcellab/monolith/templates/service.yaml, parcellab/worker-group/Chart.yaml
* set `replicas` on the Deployment to 0 if `disableReplicaCount: true` or `argoRollout.enabled: true`
* remove `-analysis` postfix in the AnalysisTemplate name (redundant)
* remove `-rollout` Service generation (we're using the ones that are already provisioned for Deployment)
* fix Rollout name generation (had no Chart name prefix)
* prevent Deployment, Service and Rollout creation for the root application if `monolith.disableDefaultAppDeployment: true`
=> fix: rework argo rollouts template

parcellab/microservice/Chart.yaml, parcellab/microservice/templates/rollout.yaml, parcellab/monolith/Chart.yaml, parcellab/monolith/templates/rollout-service.yaml, parcellab/worker-group/Chart.yaml, parcellab/worker-group/templates/rollout.yaml
Adding conditional checks for `argoRollout` before `argoRollout.enabled` to fix the following:
```
Error: template: portal/charts/monolith/templates/rollout-service.yaml:4:19: executing "portal/charts/monolith/templates/rollout-service.yaml" at <.argoRollout.enabled>: nil pointer evaluating interface {}.enabled
```
=> fix: add missing argoRollout conditional check

parcellab/common/Chart.yaml, parcellab/common/templates/_ingress.tpl, parcellab/cronjob/Chart.yaml, parcellab/microservice/Chart.yaml, parcellab/monolith/Chart.yaml, parcellab/worker-group/Chart.yaml
__Description:__\
This PR updates the `charts/parcellab/common/templates/_ingress.tpl` Helm template to ensure the Ingress is rendered correctly even when the `argoRollout` parameter is not set in the values file.
__Changes:__
- Introduce a local variable for argoRollout using `{{- $argoRollout := .Values.argoRollout | default dict -}}` to guarantee it is always defined.
- Update all references from `.Values.argoRollout.enabled` to `$argoRollout.enabled`.
- Adjust the backend service name logic to use the local variable, ensuring the correct service name is used whether or not argoRollout is set.
__Motivation:__\
Previously, if `argoRollout` was not defined in the values, the template could fail or generate an incorrect Ingress. This change makes the template robust and consistent with …
=> fix: inf-2797 argorollout values for ingress template

parcellab/common/Chart.yaml, parcellab/common/templates/_container.tpl, parcellab/common/templates/_pod.tpl, parcellab/cronjob/Chart.yaml, parcellab/microservice/Chart.yaml, parcellab/monolith/Chart.yaml, parcellab/worker-group/Chart.yaml
[INF-2837]
- Security contexts were incorrectly mapped in `_pod.tpl` template (podSecurityContext applied to containers, securityContext applied to pods)
- Init containers and extra containers were not inheriting security context settings
- This caused ArgoCD sync loops and inconsistent security policies across containers
- __Fixed security context mapping__:
- `podSecurityContext` now correctly applies to `spec.securityContext` (pod level)
- `securityContext` now correctly applies to `spec.containers[].securityContext` (container level)
- __Added security context propagation__: Init containers and extra containers now inherit security context from values
- __Added reusable security context variable__ for cleaner template code
- ✅ Resolves ArgoCD sync loop issues
- ✅ Ensures consistent …
=> fix: inf-2837 fixing bug with securityContext and podSecurityContext

parcellab/common/Chart.yaml, parcellab/common/templates/_deployment.tpl, parcellab/common/values.yaml, parcellab/cronjob/Chart.yaml, parcellab/microservice/Chart.yaml, parcellab/monolith/Chart.yaml, parcellab/worker-group/Chart.yaml
Global annotations for the deployments can now be defined with `.Values.deploymentAnnotations`, and/or on a service level with `$service.deploymentAnnotations`. If both are defined - they will be merged, which means if the service annotation has the same key - it'll overwrite the one from the root level.
=> feat: add deployment annotations

parcellab/common/Chart.yaml, parcellab/common/templates/_container.tpl, parcellab/common/templates/_pod.tpl, parcellab/cronjob/Chart.yaml, parcellab/microservice/Chart.yaml, parcellab/monolith/Chart.yaml, parcellab/worker-group/Chart.yaml
`containerEnv` can now be used in the following format:
```env_name: env_value```
It can be specified on multiple levels, such as:
* root (`.Values.containerEnv`)
* extra services (`extraServices[0].containerEnv`)
* common worker config (`worker.containerEnv`)
* workers (`workers[0].containerEnv`)
If envs are defined on multiple levels - they'll be merged together. If env with the same key is defined on multiple levels, it's value from the lower (more specific) level will take precedence. E.g. in case of `root` and `workers` level - workers level value will overwrite the root one.
Tested locally with onyx helm chart - works as described above.
=> feat: INF-2896 allow containerEnv to use map format aside from list

parcellab/cronjob/Chart.yaml, parcellab/cronjob/values.yaml, parcellab/microservice/Chart.yaml, parcellab/microservice/values.yaml, parcellab/monolith/Chart.yaml, parcellab/monolith/values.yaml
The bitnami migration towards bitnamilegacy requires the use of the bitnamilegacy repository in our dependencies
=> feat: update chart dependencies to use bitnamilegacy repository
