parcelLab/charts

parcellab/common/templates/_ingress.tpl, parcellab/microservice/Chart.yaml, parcellab/monolith/Chart.yaml, parcellab/monolith/templates/ingress.yaml, parcellab/monolith/values.yaml
Remove complexity with the multiple ingress approach (we can point to different services from a single ingress resource)
=> fix: enforce unique ingress

parcellab/cronjob/values.yaml, parcellab/microservice/values.yaml, parcellab/monolith/values.yaml, parcellab/worker-group/values.yaml
Updating nodeSelectors for charts
=> feat: updating nodeselector for charts

parcellab/monolith/Chart.yaml
Updating monolith version again to use latest common templates.
=> feat: updating monolith chart to use latest common templates

parcellab/common/Chart.yaml, parcellab/common/templates/_deployment.tpl, parcellab/cronjob/Chart.yaml, parcellab/microservice/Chart.yaml, parcellab/monolith/Chart.yaml, parcellab/worker-group/Chart.yaml
This PR allows deploys to be created with no replicas
=> feat: Support deploys with no pods

CODEOWNERS, parcellab/monolith/Chart.yaml
* Adding CODEOWNERS
* Bumping monolith chart version
=> chore: Adding CODEOWNERS

parcellab/common/Chart.yaml, parcellab/common/templates/_deployment.tpl, parcellab/cronjob/Chart.yaml, parcellab/microservice/Chart.yaml, parcellab/monolith/Chart.yaml, parcellab/worker-group/Chart.yaml
because of this the default of 'true' cannot be overwritten with 'false'.
Using 'hasKey' instead.
=> fix: default values dont work well with booleans

parcellab/common/Chart.yaml, parcellab/common/templates/_keda.tpl, parcellab/cronjob/Chart.yaml, parcellab/microservice/Chart.yaml, parcellab/monolith/Chart.yaml, parcellab/worker-group/Chart.yaml
=> chore: removing duplicate value

parcellab/common/Chart.yaml, parcellab/common/templates/_container.tpl, parcellab/common/templates/_pod.tpl, parcellab/cronjob/Chart.yaml, parcellab/microservice/Chart.yaml, parcellab/monolith/Chart.yaml, parcellab/worker-group/Chart.yaml
Adding lifecycle hooks feature in common charts
https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/
=> feat: adding lifecycle hook feature for pods

parcellab/common/Chart.yaml, parcellab/common/templates/_keda.tpl, parcellab/cronjob/Chart.yaml, parcellab/microservice/Chart.yaml, parcellab/monolith/Chart.yaml, parcellab/worker-group/Chart.yaml
=> chore: Removing ability to pause autoscaling

parcellab/common/Chart.yaml, parcellab/common/templates/_keda.tpl, parcellab/common/values.yaml, parcellab/cronjob/Chart.yaml, parcellab/cronjob/values.yaml, parcellab/microservice/Chart.yaml, parcellab/microservice/values.yaml, parcellab/monolith/Chart.yaml, parcellab/monolith/values.yaml, parcellab/worker-group/Chart.yaml, parcellab/worker-group/values.yaml
Now we can configure the scaleOnInFlight parameter. Also we don't pull the image of the container by default.
=> chore: We only use KEDA scaling with visible messages

parcellab/common/Chart.yaml, parcellab/common/templates/_keda.tpl, parcellab/cronjob/Chart.yaml, parcellab/microservice/Chart.yaml, parcellab/monolith/Chart.yaml, parcellab/worker-group/Chart.yaml
=> fix: fixing keda template creation

parcellab/common/Chart.yaml, parcellab/common/templates/_pod.tpl, parcellab/common/values.yaml, parcellab/cronjob/Chart.yaml, parcellab/microservice/Chart.yaml, parcellab/microservice/values.yaml, parcellab/monolith/Chart.yaml, parcellab/monolith/values.yaml, parcellab/worker-group/Chart.yaml, parcellab/worker-group/values.yaml
https://parcellab.atlassian.net/browse/INF-1233
Adding terminationGracePeriodSeconds parameter in common chart.
=> feat: adding terminationGracePeriodSeconds option in common chart

parcellab/common/Chart.yaml, parcellab/common/templates/_poddisruptionbudget.tpl, parcellab/cronjob/Chart.yaml, parcellab/microservice/Chart.yaml, parcellab/microservice/templates/poddisruptionbudget.yaml, parcellab/monolith/Chart.yaml, parcellab/monolith/templates/poddisruptionbudget-service.yaml, parcellab/monolith/templates/poddisruptionbudget.yaml, parcellab/worker-group/Chart.yaml
Fixing bug with podDisruptionbudget when defined in more than 2 extraservices.
=> fix: fixing podDisruptingbudget in templates

parcellab/common/Chart.yaml, parcellab/common/templates/_cronjob.tpl, parcellab/cronjob/Chart.yaml, parcellab/microservice/Chart.yaml, parcellab/monolith/Chart.yaml, parcellab/worker-group/Chart.yaml
INF-1331 fixing an attribute in the cronjob template
=> fix: correct job attribute

parcellab/common/Chart.yaml, parcellab/common/templates/_pod.tpl, parcellab/cronjob/Chart.yaml, parcellab/microservice/Chart.yaml, parcellab/monolith/Chart.yaml, parcellab/worker-group/Chart.yaml
In order to add extra annotations in pods, we defined a new block in the pod template.
=> feat: enabling pod template annotations

parcellab/common/Chart.yaml, parcellab/cronjob/Chart.yaml, parcellab/microservice/Chart.yaml, parcellab/microservice/values.yaml, parcellab/monolith/Chart.yaml
job.activeDeadlineSeconds is required so it should be in the template as well
=> fix: Update values.yaml

.github/workflows/test.yaml
Updating test workflow to create releases only of the changed charts.
=> feat: Updating test workflow to separate releases.

parcellab/common/Chart.yaml, parcellab/cronjob/Chart.yaml, parcellab/microservice/Chart.yaml, parcellab/monolith/templates/poddisruptionbudget-service.yaml, parcellab/monolith/templates/rollout-service.yaml, parcellab/worker-group/Chart.yaml
Adding template for argoRollout configuration for extra services in monolith chart.
=> feat: Adding argoRollout configuration for extra services in monolith chart.

parcellab/common/Chart.yaml, parcellab/common/templates/_rollout.tpl, parcellab/cronjob/Chart.yaml, parcellab/microservice/Chart.yaml, parcellab/monolith/Chart.yaml
Updating rollout template to use custom values for each service defined in the values file.
=> feat: Updating rollout template to use custom values for each service.

.github/workflows/release.yaml
=> chore: Updating gituhb actions.

parcellab/common/Chart.yaml, parcellab/common/templates/_pod.tpl, parcellab/cronjob/Chart.yaml, parcellab/microservice/Chart.yaml, parcellab/monolith/Chart.yaml, parcellab/worker-group/Chart.yaml
https://parcellab.atlassian.net/browse/INF-1635
Changing default `restartPolicy` to `Never` for **cronjobs** and **jobs**. This will prevent to remove the pods for failed jobs so we don't lose the logs.
=> feat: Changing default restartPolicy to Never for cronjobs and jobs.

parcellab/common/Chart.yaml, parcellab/common/templates/_pod.tpl, parcellab/microservice/Chart.yaml, parcellab/microservice/values.yaml, parcellab/monolith/Chart.yaml, parcellab/monolith/values.yaml, parcellab/worker-group/Chart.yaml, parcellab/worker-group/README.md, parcellab/worker-group/values.yaml
Adding `startupProbe` to the common pod's template
https://parcellab.atlassian.net/browse/INF-1695
=> feat: inf-1697 Add startupProbe to the pod's configuration

parcellab/monolith/Chart.yaml, parcellab/monolith/values.yaml
Removing the default timezone defined in values file for monolith.
=> feat: Removing default timezone monolith chart.

parcellab/common/Chart.yaml, parcellab/common/templates/_pod.tpl, parcellab/cronjob/Chart.yaml, parcellab/microservice/Chart.yaml, parcellab/monolith/Chart.yaml, parcellab/worker-group/Chart.yaml
Fix for https://parcellab.atlassian.net/browse/INF-1695 because of discussion here https://parcellab-tech.slack.com/archives/C03EQCRUHGF/p1723709620147899?thread_ts=1721378313.496539&cid=C03EQCRUHGF
=> fix: add startup probe to the default container level

parcellab/common/Chart.yaml, parcellab/common/templates/_container.tpl, parcellab/cronjob/Chart.yaml, parcellab/microservice/Chart.yaml, parcellab/monolith/Chart.yaml, parcellab/worker-group/Chart.yaml
Adding `command` support to the initContainers and extraContainers
=> feat: INF-1731 Use command for each init and extra Container

parcellab/common/Chart.yaml, parcellab/common/templates/_container.tpl, parcellab/cronjob/Chart.yaml, parcellab/microservice/Chart.yaml, parcellab/monolith/Chart.yaml, parcellab/worker-group/Chart.yaml
* also adding `args` support for additional containers
* removing `.secretName` from the conditional statement because it's not in use
=> fix: ExternalSecret and ConfigMap definition for additional containers

parcellab/common/templates/_pod.tpl
=> fix: close if statement

.github/workflows/release.yaml, parcellab/common/templates/_labels.tpl
Updating release pipeline to avoid loop of releases.
=> fix: Updating the release chart

parcellab/common/templates/_labels.tpl
=> fix: Removing dummy comments for release pipeline test

parcellab/cronjob/templates/cronjob-extra.yaml
=> fix: Testing updates

parcellab/cronjob/templates/cronjob-extra.yaml
=> fix: Adding dummy comment again in labels.tpl

parcellab/cronjob/templates/cronjob-extra.yaml
=> fix: Adding dummy comment in cronjob-extra.yaml

parcellab/monolith/Chart.yaml
=> fix: Pumping monolith version

.github/workflows/release.yaml, parcellab/monolith/Chart.yaml
=> feat: rolling back release pipeline

parcellab/microservice/Chart.yaml
=> fix: Pumping microservice helm chart version to fix index

parcellab/common/Chart.yaml, parcellab/common/templates/_names.tpl, parcellab/common/templates/_pod.tpl, parcellab/cronjob/Chart.yaml, parcellab/microservice/Chart.yaml, parcellab/monolith/Chart.yaml, parcellab/worker-group/Chart.yaml
Support the default image string to be overwritten by repository and/or version tag
=> feat: inf-2146 separate image attribute overrides

parcellab/common/Chart.yaml, parcellab/common/templates/_pod.tpl, parcellab/cronjob/Chart.yaml, parcellab/microservice/Chart.yaml, parcellab/monolith/Chart.yaml, parcellab/worker-group/Chart.yaml
Need this to be able to overwrite exact file when mapping configmap as volume
=> feat: add volume subPath

parcellab/common/Chart.yaml, parcellab/common/templates/_deployment.tpl, parcellab/common/templates/_hpa.tpl, parcellab/common/templates/_ingress.tpl, parcellab/cronjob/Chart.yaml, parcellab/microservice/Chart.yaml, parcellab/monolith/Chart.yaml, parcellab/worker-group/Chart.yaml
=> feat: adjust resources argorollout

.github/copilot-instructions.md
Add copilot instruction - nothing special, Copilot likely knows all these things
=> chore: add copilot-instructions.md

parcellab/common/Chart.yaml, parcellab/common/templates/_pod.tpl, parcellab/cronjob/Chart.yaml, parcellab/microservice/Chart.yaml, parcellab/monolith/Chart.yaml, parcellab/worker-group/Chart.yaml
Solves a bug in the securityContext population
=> fix: security context

parcellab/common/Chart.yaml, parcellab/common/templates/_pod.tpl, parcellab/cronjob/Chart.yaml, parcellab/microservice/Chart.yaml, parcellab/monolith/Chart.yaml, parcellab/worker-group/Chart.yaml
This fixes a bug where sidecars or initContainers are not rendered with helm.
=> fix: sidecar or initContainer reference
